### ISSUE TITLE
about play 1.7.1 log problem

### ISSUE THREAD

**Issue by liccoCode** [playframework/play1#1433]
hello,

I'm having a problem with jar referencing while writing a play project.

in dependencies.yml file, I write

  - org.apache.logging.log4j -> log4j-core 2.17.2

but, when I run  "play deps --sync",
the play project download a lot test jar in my project, actually i only need log4j-core.jar ，

please tell me how to Solve this problem， exclude all test jar.

**Comment by aleksandy** [comment]
Looks like dependency manager tries to download the all transitive dependencies include optional and test. To fix this behaviour you should prevent transitive deps using `transitive` property. But in that case you must add `log4j-api` dependency explicitly.
```yaml
- org.apache.logging.log4j -> log4j-api 2.17.2:
    transitive: false
- org.apache.logging.log4j -> log4j-core 2.17.2:
    transitive: false
```
